### ISSUE TITLE
channel notices are treated as CTCP

### ISSUE THREAD

**Issue by thegrumble** [freenode/Sigyn#11]
Non-CTCP channel notices are treated just like CTCPs (Sigyn calls them "ctcp" too) which is quite confusing from an operator perspective.
In my opinion, it would make sense to separate detection of channel notices and channel CTCPs.

**Comment by ncoevoet** [comment]
maybe i should just rename it to 'notice', because channel's CTCP can be blocked by cmode C and it doesn't make sense to trigger network ban on something channel's ops can block
