### ISSUE TITLE
Voiced users shouldn't be banned

### ISSUE THREAD

**Issue by impredicative** [freenode/Sigyn#15]
If a user is voiced in a channel, it should be considered as being whitelisted for that channel, and so it shouldn't risk being banned in that channel. I am not saying that there was an incident where a voiced user was banned, only that this feature will offer me a whitelist that I can use. The same also applies by default to channel ops.

**Comment by emersonveenstra** [comment]
I wouldn't be opposed to looking at an opt-in or opt-out version of this. I can't do it globally because some channels' moderation techniques involve setting +m and then manually voicing all users, so the spambots will have +v as well in that scenario.

**Comment by impredicative** [comment]
I vote for global with an optional opt-out, but then I may be biased.

**Comment by ncoevoet** [comment]
you can add a channelRegistry boolean for that, so it can be set globaly or per channel

**Comment by impredicative** [comment]
How do I set `ignoreVoicedUser` for a channel where Sigyn is present? Also, how do I check the preexisting Sigyn config for a channel?

**Comment by ilbelkyr** [comment]
@impredicative In the case of freenode's Sigyn instance, you can't do it yourself, but staff will generally be happy to help you out with anything you need for channels you own that Sigyn is watching.

If this is for another network and you're running your own instance, the command would be `config channel #foo plugins.Sigyn.ignoreVoicedUser True` (or `False` to turn it off again).
