### ISSUE TITLE
"suspicious joins of..." notes should ignore cloaking fake-joins

### ISSUE THREAD

**Issue by fndax** [freenode/Sigyn#16]
Sigyn sends a message when she detects a suspiciously-large number of joins from one person:

> 19:49 <+Sigyn> NOTE: [#freenode] suspicious joins of someuser alts (gecos)

This detection does not currently take into consideration whether the JOIN is immediately after a "Changing host" fakequit, and thus triggers incorrectly more often than not. It would probably be worth coding it to do so, or perhaps changing the default threshold to consider this case.

**Comment by ncoevoet** [comment]
we have reviewed a bit the mass join detection in lastest commit, after fine tunning we may suggest some per channel ban/quiet or others modes, stay tunned
