### ISSUE TITLE
Make chanop-issued unkline remove temporary patterns

### ISSUE THREAD

**Issue by thegrumble** [freenode/Sigyn#17]
Sigyn's false positives are often caused by temporary channel patterns.

In my opinion, it would make sense to remove a channel's temporary patterns when a channel op notices such a false positive and issues the `unkline` command.

**Comment by ncoevoet** [comment]
There is no link between channel's patterns and klined users, what you suggest is the ability for channel's ops to clear temporary patterns for the channel requested via unkline <nick>?

**Comment by thegrumble** [comment]
There is some sort of link: Often, false positive k-lines are triggered by someone pasting code or logfiles by accident. If there are repetetive strings, Sigyn will usually kill them for massRepeat and add an according temporary pattern.

Chanops don't have insight into Sigyn's patterns but they can identify false positives.
When a false positive is identified and Sigyn is told about it via the `unkline` command, it makes sense to remove the pattern that was created along with that false positive k-line.

**Comment by ncoevoet** [comment]
you now have a per channel / global config for that supybot.plugins.Sigyn.clearTmpPatternOnUnkline
