### ISSUE TITLE
Possibly incompatible with Charybdis 4.0 (or some IRCv3 capability)

### ISSUE THREAD

**Issue by Mikaela** [freenode/Sigyn#24]
So far we have only managed to have Sigyn KLINEing after either manually added pattern has been triggered or something has been considered as flooding.

Line that doesn't get detected is: `
[14/16:55:40]<Pirate_57771> Defendanto: Fletcher Kunsido Mikaela Mikaela2 MikaelaX Pirate_57771`

`irc.net CAP Mikaela LS :account-notify account-tag away-notify cap-notify chghost echo-message extended-join invite-notify multi-prefix sasl=PLAIN,AUTHCOOKIE,EXTERNAL,ECDSA-NIST256P-CHALLENGE server-time tls userhost-in-names`

**Comment by janicez** [comment]
Something I noticed about the bot this is a plugin for is that it doesn't support anything except op, halfop, and voice, as far as modes go.

Maybe the bot is also un-updated in other ways. Might be related.

**Comment by Mikaela** [comment]
Today we had amsg spam on ten channels (before oper took action) within two minutes and we aren't seeing anything weird in our configuration or any reason why it wouldn't have caught it. The bot was on all ten channels, and it still did nothing.

> Something I noticed about the bot this is a plugin for is that it doesn't support anything except op, halfop, and voice, as far as modes go.

Neither does Charybdis 4 as far as I am aware, or at least I remember them saying in the past to never support other modes than op/voice.

> Maybe the bot is also un-updated in other ways. Might be related.

I doubt it to be Limnoria issue as there are multiple others of them without Sigyn and I haven't seen two of mine complain about anything or heard of any issues from other people running them.

The bot also seems to have regular updates https://github.com/ProgVal/Limnoria/tags and the most green IRCv3 support table. https://ircv3.net/software/clients.html#bots

**Comment by ncoevoet** [comment]
with just that it's hard for me to know what happened : 
settings used for the detection, logs of messages of the spammer with timestamp, eventualy bot's logs

**Comment by ncoevoet** [comment]
feel free to open a new one with more details and contexts if something wrong occurs again

**Comment by Mikaela** [comment]
It turned out that the issue was caused by UTF-8 patterns.

**Comment by janicez** [comment]
*facepalm*
