### ISSUE TITLE
Log channel bad notices include cloaked host as kline target regardless of use whowas

### ISSUE THREAD

**Issue by Mikaela** [freenode/Sigyn#26]
`2018-02-18T15:20:37+0200 Defendanto (Notice) BAD: [#canada] Stella!~Stella@149.154.npj.tjj (matches #6) -> *@149.154.npj.tjj`

I think the last part should be the actual host rather than the cloaked one as that is what was klined.

**Comment by ncoevoet** [comment]
as BAD messages  shows datas before any whowas or others hostname resolutions methods, the -> * part is not accurate, i will probably remove it, and maybe replace it with a unique ID added also in private kline reason.
