### ISSUE TITLE
Defcon Modes are only set when already in oper-override

### ISSUE THREAD

**Issue by mweinelt** [freenode/Sigyn#32]
This is the `else` tree of `defcon()`, but the code has been copied to roughly six other codepaths.

When defconf modes should be set but the bot has not enabled oper-override yet it will enable oper-override and not set defconf modes.
I believe this is because the latter is done in the `else` clause, but it probably shouldn't be in an else clause at all.

```python3
                i.defcon = time.time()
                self.logChannel(irc,"INFO: ignores lifted and abuses end to klines for %ss by %s" % (self.registryValue('defcon'),msg.nick))
                # todo check current bot's umode
                if not i.god:
                    irc.sendMsg(ircmsgs.IrcMsg('MODE %s +p' % irc.nick))
                else:
                    for channel in irc.state.channels:
                        if irc.isChannel(channel) and self.registryValue('defconMode',channel=channel):
                            if not 'z' in irc.state.channels[channel].modes:
                                if irc.nick in list(irc.state.channels[channel].ops):
                                    irc.sendMsg(ircmsgs.IrcMsg('MODE %s +qz $~a' % channel))
                                else:
                                    irc.sendMsg(ircmsgs.IrcMsg('MODE %s +oqz %s $~a' % (channel,irc.nick)))
```

**Comment by mweinelt** [comment]
I would be willing to submit a PR for this, but we should probably discuss whether or not my concern is correct.

**Comment by edk0** [comment]
that's because if the bot is not already in override mode it sends the mode changes when it gets +p: https://github.com/freenode/Sigyn/blob/master/plugin.py#L1485

**Comment by mweinelt** [comment]
Shouldn't be necessary since command execution happens in order, but yeah, at first glance that should work. I had several occasions though, where it would not set `+zq $~a` when entering defcon mode for a channel - weird.

**Comment by edk0** [comment]
was it configured to do so for that channel? that setting isn't on by default, needs to be requested from staff

**Comment by mweinelt** [comment]
```
16:53 <@hexa-> .config supybot.plugins.Sigyn.defcon 
16:53 <Sigyn> OP: [#hackint-abuse] <hexa-> .config supybot.plugins.sigyn.defcon
16:53 <Sigyn> hexa-: 1            
16:53 <@hexa-> .config supybot.plugins.Sigyn.defconMode
16:53 <Sigyn> OP: [#hackint-abuse] <hexa-> .config supybot.plugins.sigyn.defconmode
16:53 <Sigyn> hexa-: Global: True; #hackint-abuse: True
```

**Comment by ncoevoet** [comment]
Because there is always delays between sending a command to server and that command being processed by the server, so the +p is handle in doMode once Sigyn has oper overrides on.
I can't reproduce your issue with defconMode, but anyway i will refactor this part...
