### ISSUE TITLE
ns id flood kill reason is just the user's hostmask

### ISSUE THREAD

**Issue by thegrumble** [freenode/Sigyn#38]
https://github.com/freenode/Sigyn/blob/d39d269b5e3bc75d31a4b3a0729056b1b25f2461/plugin.py#L2734-L2738
A more user-friendly kill message should be chosen in my opinion

**Comment by examknow** [comment]
Is this issue still active? It seems the issue was resolved many years ago. If this is the case, then there's not much use in leaving the issue open.
