### ISSUE TITLE
repeatPattern

### ISSUE THREAD

**Issue by sacredland** [freenode/Sigyn#41]
Error: 'supybot.plugins.Sigyn.repeatPattern' is not a valid configuration variable.

**Comment by ncoevoet** [comment]
Hello, what are you trying to achieve ?

**Comment by examknow** [comment]
> Error: 'supybot.plugins.Sigyn.repeatPattern' is not a valid configuration variable.

According to config.py, the 'repeatPattern' config variable doesn't actually exist. I'm not really sure why it's been in the docs since 2017.
